blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('podcast/', views.podcast, name='blog-podcast'),
]

momtazsite2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('courses/', include('courses.urls')),
    path('', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('accounting/', include('accounting.urls')),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('', views.home, name='dashboard-home'),
    path('register/', views.register, name='users-register'),
    path('basic_registration/', views.basic_registration, name='basic_registration'),
    path('student_register/', views.student_register, name='users-student_register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='users-logout'),
    path('profile/', views.profile, name='users-profile'),
    path('password_reset/', views.reset_password, name='password_reset'),
    path('password_reset/done/', views.reset_password_done, name='password_reset_done'),
    path('password_change/', views.change_password, name='password_change'),
    path('password_change/done/', views.change_password_done, name='password_change_done'),
    path('register_validation_code/', views.register_validation_code, name='users-register_validation_code'),
]

users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Role(models.Model):
    role = models.CharField(max_length=30, default='')
    permission = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.role


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    father_name = models.CharField(max_length=30, default='')
    phone = models.CharField(max_length=30, default='', unique=True)
    online_or_offline = models.IntegerField(default=0)
    institute = models.CharField(max_length=30, default='')
    role = models.ForeignKey(Role, on_delete=models.CASCADE, default=4)
    profile_picture = models.ImageField(upload_to='profile_pictures', blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.user.username


class Student(models.Model):
    student = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    major = models.IntegerField(default=0)
    grade = models.IntegerField(default=0)
    school = models.CharField(max_length=30, default='')
    mother_phone = models.CharField(max_length=30, default='')
    father_phone = models.CharField(max_length=30, default='')
    home_phone = models.CharField(max_length=30, default='')
    support_id = models.IntegerField(default=0)
    counselor_id = models.IntegerField(default=0)
    manager_id = models.IntegerField(default=0)
    support_name = models.CharField(max_length=30, default='')
    counselor_name = models.CharField(max_length=30, default='')
    manager_name = models.CharField(max_length=30, default='')
    created_at = models.DateTimeField(default=timezone.now)

    def user_id(self):
        return self.student.user.id

    def __str__(self):
        return self.student.user.username


class Exam(models.Model):
    exam_name = models.CharField(max_length=30, default='')
    exam_date = models.DateTimeField(default=timezone.now)
    exam_score = models.IntegerField(default=0)
    exam_student = models.ForeignKey(Student, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def student_id(self):
        return self.exam_student.student.id

    def __str__(self):
        return self.exam_name


class SumOfStudy(models.Model):
    sum_student = models.ForeignKey(Student, on_delete=models.CASCADE)
    start_time = models.TimeField(default=timezone.now)
    end_time = models.TimeField(default=timezone.now)
    test_count = models.IntegerField(default=0)
    study_time = models.IntegerField(default=0)
    description = models.TextField(default='', blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def student_id(self):
        return self.sum_student.student.id

    def __str__(self):
        return self.sum_student.student.user.username

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Student, UserProfile, Role
from dashboard.models import SendSMS
import secrets
import re


def get_support_names():
    support_names = []
    for support in UserProfile.objects.filter(role__role='support'):
        support_names.append((support.user_id, support.user.username))
    return support_names


def get_counselor_names():
    counselor_names = []
    for counselor in UserProfile.objects.filter(role__role='counselor'):
        counselor_names.append((counselor.user_id, counselor.user.username))
    return counselor_names


def get_manager_names():
    manager_names = []
    for manager in UserProfile.objects.filter(role__role='manager'):
        manager_names.append((manager.user_id, manager.user.username))
    return manager_names


class ValidationCodeForm(forms.Form):
    validation_code = forms.CharField(max_length=8, required=True)
    verifier = 0

    def clean_validation_code(self):
        code = self.cleaned_data['validation_code']
        if code != self.verifier:
            raise forms.ValidationError('کد تایید صحیح نیست')
        return code


class BasicRegistration(UserCreationForm):
    phone = forms.IntegerField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    father_name = forms.CharField(max_length=30, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].required = False
        self.fields['password1'].required = False
        self.fields['password2'].required = False
        self.fields['username'].widget = forms.HiddenInput()
        self.fields['password1'].widget = forms.HiddenInput()
        self.fields['password2'].widget = forms.HiddenInput()

    code = secrets.token_hex(4)

    def send_sms(self):
        phone = self.cleaned_data['phone']
        phone_number = str(phone)
        if UserProfile.objects.filter(phone=phone).exists():
            raise forms.ValidationError('شماره تلفن وارد شده قبلا ثبت شده است')
        elif not re.match(r'^9\d{9}$', str(phone_number)):
            raise forms.ValidationError('شماره تلفن وارد شده صحیح نیست')
        else:
            ValidationCodeForm.verifier = self.code
            text = 'کد تایید شما: ' + self.code
            SendSMS().send(to=phone, text=text)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.username = self.cleaned_data['phone']
        user.set_password(self.code)
        if commit:
            user.save()
            userprofile = UserProfile.objects.create(user=user)
            userprofile.father_name = self.cleaned_data['father_name']
            userprofile.phone = self.cleaned_data['phone']
            if commit:
                userprofile.save()
        return user


class UserRegisterForm(forms.Form):
    online_or_offline = forms.ChoiceField(choices=[('1', 'online'), ('0', 'offline')], required=True)
    role = forms.ModelChoiceField(queryset=Role.objects.all(), required=True)
    institute = forms.CharField(max_length=30, required=True)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    class Meta:
        fields = ['online_or_offline', 'role', 'institute']

    def save(self, commit=True):
        user = self.user
        userprofile = UserProfile.objects.get(user=user)
        userprofile.online_or_offline = self.cleaned_data['online_or_offline']
        userprofile.role = self.cleaned_data['role']
        userprofile.institute = self.cleaned_data['institute']
        if commit:
            userprofile.save()
        return userprofile


class StudentRegisterForm(forms.Form):
    major = forms.ChoiceField(choices=[('1', 'math'), ('2', 'law'), ('3', 'biology')], required=True)
    grade = forms.ChoiceField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], required=True)
    school = forms.CharField(max_length=30, required=True)
    mother_phone = forms.IntegerField(required=True)
    father_phone = forms.IntegerField(required=True)
    home_phone = forms.IntegerField(required=True)
    support_name = forms.CharField(max_length=30, required=True)
    counselor_name = forms.CharField(max_length=30, required=True)
    manager_name = forms.CharField(max_length=30, required=True)

    class Meta:
        fields = ['major', 'grade', 'mother_phone', 'father_phone', 'home_phone', 'support_name', 'counselor_name', 'manager_name']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        user = self.user
        userprofile = UserProfile.objects.get(user=user)
        student = Student.objects.create(student=userprofile)
        student.major = self.cleaned_data['major']
        student.grade = self.cleaned_data['grade']
        student.school = self.cleaned_data['school']
        student.mother_phone = self.cleaned_data['mother_phone']
        student.father_phone = self.cleaned_data['father_phone']
        student.home_phone = self.cleaned_data['home_phone']
        student.support_id = self.cleaned_data['support_name']
        student.counselor_id = self.cleaned_data['counselor_name']
        student.manager_id = self.cleaned_data['manager_name']
        support = UserProfile.objects.get(user_id=student.support_id)
        student.support_name = support.user.username
        counselor = UserProfile.objects.get(user_id=student.counselor_id)
        student.counselor_name = counselor.user.username
        manager = UserProfile.objects.get(user_id=student.manager_id)
        student.manager_name = manager.user.username

        if commit:
            student.save()
        return user

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import StudentRegisterForm, BasicRegistration, ValidationCodeForm, UserRegisterForm, get_support_names
from dashboard.forms import SMSPasswordResetForm
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from .models import Role, UserProfile


def home(request):
    return render(request, 'users/home.html')


def basic_registration(request):
    if request.method == 'POST':
        form = BasicRegistration(request.POST)
        if form.is_valid():
            form.send_sms()
            user = form.save()
            request.session['user_id'] = user.id
            return redirect('users:users-register_validation_code')
    else:
        form = BasicRegistration()
    return render(request, 'users/register_validation.html', {'form': form})


def register_validation_code(request):
    if request.method == 'POST':
        form = ValidationCodeForm(request.POST)
        if form.is_valid():
            return redirect('users:users-register')
    else:
        form = ValidationCodeForm()
    return render(request, 'users/register_validation_code.html', {'form': form})


def register(request):
    user = None
    roles = Role.objects.all()
    if request.method == 'POST':
        user_id = request.session.get('user_id')
        user = User.objects.get(id=user_id)
        form = UserRegisterForm(request.POST, user=user)
        if form.is_valid():
            messages.success(request, f'Account created for {form.cleaned_data.get("username")}!')
            form.save()
            if user.userprofile.role_id == 4:
                return redirect('users:users-student_register')
            return redirect('users:users-login')
    else:
        form = UserRegisterForm(request.POST, user=user)
    context = {
        'form': form,
        'roles': roles,
    }
    return render(request, 'users/register.html', context)


def student_register(request):
    user = None
    support_names = UserProfile.objects.filter(role__role='پشتیبان')
    counselor_names = UserProfile.objects.filter(role__role='مشاور')
    manager_names = UserProfile.objects.filter(role__role='مدیر')
    if request.method == 'POST':
        user_id = request.session.get('user_id')
        user = User.objects.get(id=user_id)
        form = StudentRegisterForm(request.POST, user=user)
        if form.is_valid():
            form.save()
            return redirect('users:users-login')
    else:
        form = StudentRegisterForm(request.POST, user=user)
    context = {
        'form': form,
        'support_names': support_names,
        'counselor_names': counselor_names,
        'manager_names': manager_names,
    }
    return render(request, 'users/student_register.html', context)


def reset_password(request):
    form = SMSPasswordResetForm()
    if request.method == 'POST':
        form = SMSPasswordResetForm(request.POST)
        if form.is_valid():
            return redirect('password_reset_done')
    return render(request, 'users/reset_password.html', {'form': form})


def reset_password_done(request):
    return render(request, 'users/reset_password_done.html')


@login_required
def profile(request):
    return render(request, 'users/profile.html')


@login_required
def change_password(request):
    return auth_views.PasswordChangeView.as_view(template_name='users/password_change.html')(request)


@login_required
def change_password_done(request):
    return auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html')(request)

users/templates/users/login.html
<!DOCTYPE html>
{% load static %}
<html dir="rtl">
<head>
	<title>login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'users/login.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
<div class="login">
	<center><!--<h2 class="active"> <img class="profile" ></img> </h2>-->
		<div class="profile"><i class="fas fa-user"></i></div>
	</center>

    <form method="post">
        {% csrf_token %}

        <input type="text" class="text" name="username" placeholder="نام کاربری...">
         <span>نام کاربری</span>

        <br>

        <br>

        <input type="password" class="text" name="password" placeholder="رمز عبور...">
        <span>رمز عبور</span>
        <br>

        <input type="checkbox" id="checkbox-1-1" class="custom-checkbox" />
        <label for="checkbox-1-1">مرا به خاطر بسپار</label>

        <button class="signin">
          ورود
        </button>


        <hr>

        <a href="{% url 'users:password_reset'%}">آیا رمز خود را فراموش کرده اید؟</a>
    </form>

</div>
</body>
</html>

users/templates/users/logout.html
{% block content %}
        <h2>logged out</h2>
        <div class="border-top pt-3">
          <small class="text-muted">
             <a href="/users/login" >login</a>
          </small>
        </div>
{% endblock %}

users/templates/users/password_change.html
{% extends 'users/base.html' %}

{% block content %}
  <h2>Change Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change Password</button>
  </form>
{% endblock %}

users/templates/users/password_change_done.html
{% block content %}
  <div class="container mt-5">
    <h2>Password Changed Successfully</h2>
    <p>Your password has been changed successfully. You may now log in with your new password.</p>
    <a href="/users/login">Return to Home</a>
  </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<h1>{{user.username}}</h1>

{% endblock %}

users/templates/users/register.html
<!DOCTYPE html>
{% load static %}
<html dir="rtl">
<head>
    <meta charset="utf-8">
	<title>login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'users/login.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
<div class="login">
	<center><!--<h2 class="active"> <img class="profile" ></img> </h2>-->
		<div class="profile"><i class="fas fa-users"></i></div>
	</center> <br>
    <form method="post">
        {% csrf_token %}
    <select name="role" style="color: wheat;">
		<option value="" disabled selected>نقش</option>
        {% for role in roles %}
        <option value="{{ role.id }}">{{ role.role }}</option>
        {% endfor %}
	</select>
     <span>نوع شرکت کننده</span>

    <br>
    <br>

    <select name="online_or_offline" style="color: wheat;">
        <option value="" disabled selected>نحوه شرکت</option>
        <option value="0">حضوری</option>
        <option value="1">غیر حضوری</option>
    </select>
    <span>نحوه شرکت</span>
    <br>
    <br>

    <input type="text" class="text" name="institute" placeholder="اموزشگاه" required>
    <span>نام اموزشگاه</span>
    <br>
    <br>


    
    <button class="signin">
      پایان
    </button>
    <hr>
    </form>

</div>
</body>
</html>

users/templates/users/register_validation.html
<!doctype html>
{% load static %}
<html dir="rtl">
<head>
<meta charset="utf-8">
<title>ثبت نام</title>
	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'users/login.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
</head>
<body>
<div class="login" style="height: 600px;">
	<center><!--<h2 class="active"> <img class="profile" ></img> </h2>-->
		<div class="profile"><i class="fas fa-user"></i></div>
	</center>
  <form method="post">
    {% csrf_token %}
    <input type="text" class="text" name="phone" placeholder="شماره موبایل...">
     <span>شماره موبایل</span>
      <br>
    
     <br>

    <input type="text" class="text" name="first_name" placeholder="نام">
    <span>نام</span>
    <br>
	<br>

    <input type="text" class="text" name="last_name" placeholder="نام خانوادگی">
    <span>نام خانوادگی</span>
    <br>
    <br>
      <input type="text" class="text" name="father_name" placeholder="نام پدر">
    <span>نام پدر</span>



	<a href="{% url 'users:users-register_validation_code'%}" style="text-decoration: none; top: 0;"><button class="signin">
       ادامه
    </button></a>


    <hr>

    <a href="{% url 'users:users-login' %}">آیا اکانت دارید؟</a>
  </form>

</div>
</body>
</html>

users/templates/users/register_validation_code.html
<!doctype html>
{% load static %}
<html dir="rtl">
<head>
<meta charset="utf-8">
<title>ثبت نام</title>
	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'users/login.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
</head>
<body>
<div class="login" style="height: 250px; margin-top: 30px;">

	<center><!--<h2 class="active"> <img class="profile" ></img> </h2>-->
		<div class="profile"><i class="fas fa-phone"></i></div>
	</center>
    <form method="POST">
        {% csrf_token %}
        <input type="text" class="text" name="validation_code" placeholder="129393">
        <span>کد ارسالی</span>
	    <a href="reg2.html"  style="top: 0; text-decoration: none;"><button class="signin" style="margin-top: 5px;">
           ادامه
        </button></a>
    </form>

</div>
</body>
</html>

users/templates/users/reset_password.html
{% block content %}
  <h2>Reset Password</h2>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reset Password</button>
  </form>
{% endblock %}

users/templates/users/reset_password_done.html
{% block content %}
    <h1>code has been sent, plz try to login to your acount and chenage your password for security reasons</h1>
    <a href="/users/login/">Login</a>

{% endblock %}

users/templates/users/student_register.html
<!DOCTYPE html>
{% load static %}
<html dir="rtl">
<head>
    <meta charset="utf-8">
	<title>login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'users/login.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
<div class="login">
	<center><!--<h2 class="active"> <img class="profile" ></img> </h2>-->
		<div class="profile"><i class="fas fa-users"></i></div>
	</center> <br>
    <form method="post">
        {% csrf_token %}
    <select name="major" style="color: wheat;">
		<option value="" disabled selected>رشته</option>
        <option value="1">ریاضی فیزیک</option>
        <option value="2">انسانی</option>
        <option value="3">تجربی</option>
	</select>
     <span>رشته</span>

    <br>
    <br>

    <select name="grade" style="color: wheat;">
        <option value="" disabled selected>مقطع تحصیلی</option>
        <option value="7">هفتم</option>
        <option value="8">هشتم</option>
        <option value="9">نهم</option>
        <option value="10">دهم</option>
        <option value="11">یازدهم</option>
        <option value="12">دوازدهم</option>
    </select>
    <span>مقطع تحصیلی</span>
    <br>
    <br>

    <input type="text" class="text" name="school" placeholder="مدرسه" required>
    <span>نام مدرسه</span>
    <br>
    <br>

    <input type="text" class="text" name="mother_phone" placeholder="شماره مادر" required>
    <span>شماره مادر</span>
    <br>
    <br>

    <input type="text" class="text" name="father_phone" placeholder="شماره پدر" required>
    <span>شماره پدر</span>
    <br>
    <br>

    <input type="text" class="text" name="home_phone" placeholder="شماره منزل" required>
    <span>شماره منزل</span>
    <br>
    <br>

    <select name="support_name" style="color: wheat;">
        <option value="" disabled selected>نام پشتیبان</option>
        {% for support in support_names %}
        <option value="{{ support.user.id }}">{{ support.user.username }}</option>
        {% endfor %}
    </select>
    <span>نام پشتیبان</span>
    <br>
    <br>

    <select name="counselor_name" style="color: wheat;">
        <option value="" disabled selected>نام مشاور</option>
        {% for counselor in counselor_names %}
        <option value="{{ counselor.user.id }}">{{ counselor.user.username }}</option>
        {% endfor %}
    </select>
    <span>نام مشاور</span>
    <br>
    <br>

    <select name="manager_name" style="color: wheat;">
        <option value="" disabled selected>نام مدیر</option>
        {% for manager in manager_names %}
        <option value="{{ manager.user.id }}">{{ manager.user.username }}</option>
        {% endfor %}
    </select>
    <span>نام مدیر</span>
    <br>
    <br>



    
    <button class="signin">
      پایان
    </button>
    <hr>
    </form>

</div>
</body>
</html>