blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='blog-home'),
    path('podcast/', views.podcast, name='blog-podcast'),
]

dashboard/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='dashboard-home'),
    path('about/', views.about, name='dashboard-about'),
    path('ticket/', views.ticket, name='dashboard-ticket'),
    path('all_tickets/', views.all_tickets, name='dashboard-all_tickets'),
    path('card_slider/', views.card_slider, name='dashboard-card_slider'),
]

momtazsite2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('courses/', include('courses.urls')),
    path('', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('accounting/', include('accounting.urls')),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('', views.home, name='dashboard-home'),
    path('register/', views.register, name='users-register'),
    path('basic_registration/', views.basic_registration, name='basic_registration'),
    path('student_register/', views.student_register, name='users-student_register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='users-logout'),
    path('profile/', views.profile, name='users-profile'),
    path('password_reset/', views.reset_password, name='password_reset'),
    path('password_reset/done/', views.reset_password_done, name='password_reset_done'),
    path('password_change/', views.change_password, name='password_change'),
    path('password_change/done/', views.change_password_done, name='password_change_done'),
    path('register_validation_code/', views.register_validation_code, name='users-register_validation_code'),
]

dashboard/models.py
from django.db import models
from django.utils import timezone
from users.models import UserProfile
from melipayamak import Api


class CounselingRequest(models.Model):
    name = models.CharField(max_length=30, default='')
    phone = models.IntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now)
    access_code = models.IntegerField(default=0)
    description = models.TextField(default='')

    def __str__(self):
        return self.name


class SliderImage(models.Model):
    image = models.ImageField(upload_to='slider_images', blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    title = models.CharField(max_length=30, default='')

    def __str__(self):
        return self.title


class Ticket(models.Model):
    title = models.CharField(max_length=30, default='')
    pay_request = models.IntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now)
    description = models.TextField(default='')
    sender = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    receiver = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,null=True, related_name='receiver')
    sms = models.BooleanField(default=False)

    def sender_id(self):
        return self.sender.user.id

    def receiver_id(self):
        return self.receiver.user.id

    def __str__(self):
        return self.title


class Option(models.Model):
    option_key = models.CharField(max_length=30, default='')
    option_value = models.CharField(max_length=100, default='')
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.option_key


class SendSMS(models.Model):

    to = models.CharField(max_length=100, default='')
    text = models.CharField(max_length=100, default='')

    def send(self, to, text):
        username = Option.objects.get(option_key='username').option_value
        password = Option.objects.get(option_key='password').option_value
        sender = Option.objects.get(option_key='sender_number').option_value
        api = Api(username, password)
        sms = api.sms()
        response = sms.send(to=to, _from=sender, text=text)
        return response

dashboard/forms.py
from django import forms
from .models import CounselingRequest, SendSMS, Ticket
from users.models import UserProfile
import secrets
from django.contrib.admin.widgets import FilteredSelectMultiple


class CounselingRequestForm(forms.ModelForm):
    class Meta:
        model = CounselingRequest
        fields = ('name', 'phone', 'description')

    def __init__(self, *args, **kwargs):
        super(CounselingRequestForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})

    def save(self, commit=True):
        counseling_request = super(CounselingRequestForm, self).save(commit=False)
        counseling_request.name = self.cleaned_data['name']
        counseling_request.phone = self.cleaned_data['phone']
        counseling_request.description = self.cleaned_data['description']
        if commit:
            counseling_request.save()
        return counseling_request


class SendSMSForm(forms.ModelForm):

    users = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = SendSMS
        fields = ('users', 'text')

    def clean(self):
        cleaned_data = super().clean()
        users = cleaned_data.get('users')
        text = cleaned_data.get('text')
        for user in users:
            SendSMS(to=user.phone, text=text).send(to=user.phone, text=text)
        return cleaned_data


class SMSPasswordResetForm(forms.Form):
    phone = forms.CharField(max_length=11, required=True)

    def send_sms(self, phone, token):
        message = 'کد بازیابی رمز عبور شما: ' + token
        SendSMS().send(to=phone, text=message)

    def clean(self):
        cleaned_data = super().clean()
        phone = cleaned_data.get('phone')

        if UserProfile.objects.filter(phone=phone).exists():
            token = secrets.token_hex(4)
            user = UserProfile.objects.get(phone=phone).user
            user.set_password(token)
            user.save()
            self.send_sms(phone=phone, token=token)
        else:
            raise forms.ValidationError('شماره موبایل وارد شده در سیستم ثبت نشده است.')
        return cleaned_data


class TicketForm(forms.ModelForm):
    receivers = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all(),
                                               widget=FilteredSelectMultiple('receivers', False))

    class Meta:
        model = Ticket
        fields = ['title', 'pay_request', 'description', 'receivers', 'sender', 'sms']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(TicketForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        sender = cleaned_data.get('sender')
        receivers = cleaned_data.get('receivers')
        for receiver in receivers:
            Ticket.objects.create(sender=sender, receiver=receiver, title=cleaned_data['title'],
                                  description=cleaned_data['description'], pay_request=cleaned_data['pay_request'])
            if cleaned_data['sms']:
                SendSMS().send(to=receiver.phone, text=self.cleaned_data['title'])
        return cleaned_data


class StudentTicketForm(forms.ModelForm):

    class Meta:
        model = Ticket
        fields = ['title', 'description']

dashboard/views.py
from django.shortcuts import render, redirect
from .forms import StudentTicketForm
from users.models import UserProfile
from .models import Option, Ticket, SliderImage
from courses.models import Tutorial


def home(request):
    slider_images = SliderImage.objects.all()
    tutorials = Tutorial.objects.all()
    user = request.user

    context = {
        'slider_images': slider_images,
        'tutorials': tutorials,
        'user': user,
    }
    return render(request, 'dashboard/dashboard.html', context)


def card_slider(request):
    users = UserProfile.objects.all()

    context = {
        'users': users,
    }
    return render(request, 'dashboard/cardslider.html', context)


def about(request):
    return render(request, 'dashboard/podcast.html', {'title': 'About'})


def ticket(request):
    if request.method == 'POST':
        form = StudentTicketForm(request.POST)
        form.instance.sender = UserProfile.objects.get(user=request.user)
        form.instance.receiver = UserProfile.objects.get(user__id=Option.objects.get(option_key='ticket_receiver').option_value)
        if form.is_valid():
            form.save()
            return redirect('dashboard-home')
    else:
        form = StudentTicketForm()
    return render(request, 'dashboard/ticket.html', {'form': form})


def all_tickets(request):
    tickets_sent = Ticket.objects.filter(sender=request.user.userprofile)
    tickets_received = Ticket.objects.filter(receiver=request.user.userprofile)

    return render(request, 'dashboard/all_tickets.html', {'tickets_sent': tickets_sent, 'tickets_received': tickets_received})

dashboard/templates/dashboard/about.html
{% extends 'dashboard/base.html' %}
{% block content %}
    <h1>dashboard about</h1>
{% endblock %}

dashboard/templates/dashboard/all_tickets.html
{% extends 'dashboard/base.html' %}

{% block content %}
  <h1>All Tickets</h1>

  <h2>Tickets Sent</h2>
  <ul>
    {% for ticket in tickets_sent %}
      <li>{{ ticket.title }} - {{ ticket.created_at }}</li>
    {% empty %}
      <li>No tickets sent.</li>
    {% endfor %}
  </ul>

  <h2>Tickets Received</h2>
  <ul>
    {% for ticket in tickets_received %}
      <li>{{ ticket.title }} - {{ ticket.created_at }}</li>
    {% empty %}
      <li>No tickets received.</li>
    {% endfor %}
  </ul>
{% endblock %}

dashboard/templates/dashboard/base.html
<!doctype html>
{% load static %}
<html dir="rtl">
<head>
<meta charset="utf-8">
<title>test1</title>
 <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Łukasz Holeczek">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    <title>CoreUI Free Bootstrap Admin Template</title>

    <link rel="stylesheet" href="{% static 'dashboard/newCss/sk/page1.css' %}">
	<link rel="stylesheet" href="{% static 'dashboard/newCss/footer/footer.css' %}">
	<script src="{% static 'dashboard/newCss/slider/slider.js' %}"></script>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
	<link rel="stylesheet" href="{% static 'dashboard/newCss/slider/slider2.css' %}">
	<!--for sildeshow-->


	<!--for sildeshow-->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
	<!--<link rel="stylesheet" href="newCss/footer.css">-->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'dashboard/assets/favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'dashboard/assets/favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'dashboard/assets/favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'dashboard/assets/favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'dashboard/assets/favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'dashboard/assets/favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'dashboard/assets/favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'dashboard/assets/favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'dashboard/assets/favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dashboard/assets/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'dashboard/assets/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'dashboard/assets/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'dashboard/assets/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'dashboard/assets/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'dashboard/myTestFolder/momo.jpg' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- Vendors styles-->
    <link rel="stylesheet" href="{% static 'dashboard/vendors/simplebar/css/simplebar.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/css/vendors/simplebar.css' %}">
    <!-- Main styles for this application-->
    <link href="{% static 'dashboard/css/style.css' %}" rel="stylesheet">
    <!-- We use those styles to show code examples, you should remove them in your application.-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/themes/prism.css">
    <link href="{% static 'dashboard/css/examples.css' %}" rel="stylesheet">
    <!-- Global site tag (gtag.js) - Google Analytics-->
    <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-118965717-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
        dataLayer.push(arguments);
      }
      gtag('js', new Date());
      // Shared ID
      gtag('config', 'UA-118965717-3');
      // Bootstrap ID
      gtag('config', 'UA-118965717-5');
    </script>
    <link href="{% static 'dashboard/vendors/@coreui/chartjs/css/coreui-chartjs.css' %}" rel="stylesheet">

</head>
<body>
   {% include 'dashboard/header.html' %}
   {% block content %}
   {% endblock %}
   {% include 'dashboard/footer.html' %}

<script src="{% static 'dashboard/vendors/@coreui/coreui/js/coreui.bundle.min.js' %}"></script>
    <script src="{% static 'dashboard/vendors/simplebar/js/simplebar.min.js' %}"></script>
    <!-- Plugins and scripts required by this view-->
    <script src="{% static 'dashboard/vendors/chart.js/js/chart.min.js' %}"></script>
    <script src="{% static 'dashboard/vendors/@coreui/chartjs/js/coreui-chartjs.js' %}"></script>
    <script src="{% static 'dashboard/vendors/@coreui/utils/js/coreui-utils.js' %}"></script>
    <script src="{% static 'dashboard/js/main.js' %}"></script>
    <script>
    </script>
</body>
</html>

dashboard/templates/dashboard/dashboard.html
<!DOCTYPE html>
{% load static %}
<html dir="rtl">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<style type="text/css">
		body{
			background-color: #202020;
		}
		header nav ul li:hover{
			opacity: 50%;
			transition: 0.5s;
			transform: scale(0.9);
		}
		nav ul li:hover{
			opacity: 70%;
			transition: 0.5s;
			transform: scale(0.9);
			transform: translateY(-5px);
		}
		.carousel-item img{
			height: 70vh;
		}

        header nav button{
            height: 50%;
            border: none;
            border-radius: 15px;
            font-size: 15px;
            margin-left: 3px;
            width: 100px;
            font-style: bold;
        }
        header nav button:hover{
            transform: scale(0.9);
            background-color: yellow;
            color: black;
            transform: translateY(-5px);
            transition: 0.5s;
        }
        /*.divImage{
            border: none;
            border-radius: 50%;
            background-color: yellow;
        }
        .divImage img{
            background-size: cover;
            border: none;
            display: inline-block;
        }*/
		.collapse{
			justify-content: center;
		}
        .nav-new{
                margin-left: 20px;
            }
		.dropdown1{
			background-color: #202020;
			width: 200px;
			float: left;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
			position: absolute;
			z-index: 5;
			display: none;
		}
		.dropdown1 ul li{
			/*float: left;
			text-align: left;*/
		}
		.dropdown1 ul li a{
			padding: 10px 0px 10px 0px;
			color:white;
			position: inherit;
			display: inline-block;
			text-align: left;
			text-decoration: none;
			float: left;
		}
		.dropdown1 ul li a i{
			margin-top: 2px;
			margin-right: 5px;
		}
		.dropdown1 ul li a:hover{

			color: yellow;
			transform: scale(1.2);

			transition: 0.5s;
		}
		.float-start button:hover{
			background-color: hsla(0,0%,100%,0.00);
			color: yellow;
		}
		@media only screen and(max-width: 600px){
			.carousel-item img{
			height: 50vh;
		}
            .nav-new{
                margin-left: 50px;
            }
		}
	</style>
	<script type="text/javascript">
		function blockDropDown(){
			if(document.getElementById("drop1").value == 1){
			    document.getElementById("drop1").style.display = "block";
				document.getElementById("drop1").value = 0;
			   }else{
				   document.getElementById("drop1").style.display = "none";
					document.getElementById("drop1").value = 1;
			   }
		}
	</script>
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard/search.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard/page1.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard/footer.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard/responsive.css' %}">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>سایت مشاوره</title>
	<!--for bootstrap-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
	<!--for bootstrap-->
	<!--for searchBox-->
	<!--for searchBox-->
	    <header class="bg-dark p-1 d-block">
	    	<nav class="navbar navbar-expand-lg text-white">
  <a class="navbar-brand" href="#"><span class="text-white">Mom</span><span style="color: orange;">taz</span></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!--<div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link text-white" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="#">login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="#">registary</a>
      </li>
    </ul>
  </div>-->
  <div class="container h-100 justify-content-start">
      <div class="d-flex justify-content-center h-100">
        <div class="searchbar">
          <input class="search_input" id="search" type="text" name="" placeholder="Search...">
          <a href="#" class="search_icon"><i class="fas fa-search"></i></a>
        </div>
      </div>
    </div>
                <div class="float-start text-white p-2 d-flex">
					{% if not user.is_authenticated %}
                    <a href="{% url 'users:users-login' %}" style="text-decoration: none; height: 100%;"><button type="button" class="btn btn-warning" style="font-size: 15px;">ورود</button></a>
					<a href="{% url 'users:basic_registration' %}" style="text-decoration: none; height: 100%;"><button type="button" class="btn btn-warning" style="font-size: 15px;">ثبت نام</button></a>
					{% else %}
					<div   style=" position: relative; display: inline-block;" dir="ltr">
						<div class="profile" onClick="blockDropDown();">

					</div>
					<div id="drop1" class="dropdown1" dir="rtl" value="1">
						<p style="text-align: center; color: white; padding-top: 3px;
								  margin-bottom: -2px;">{{user.username}}</p><hr>
						<ul>
							<li><a href="{% url 'users:users-profile' %}">profile<i class="fas fa-user"></i></a></li>
                            <li><a href="{% url 'users:users-profile' %}">admin page<i class="fas fa-bars"></i></a></li>
							<li><a href="">logout<i class="fa-solid fa-right-from-bracket"></i></a></li>
						</ul>
						</div>

					</div>
					{% endif %}
                </div>
                <!--<div class="divImage"><img src="" class="img-fluid" alt="..."></div>-->
</nav>
	    </header>
	    <div class="text-white" style="background-color: #202020;">
	    	<nav class="navbar navbar-expand-sm navbar-dark">
            <div class="container">
                <button class="navbar-toggler ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#n_bar" aria-controls="navbarNavAltMarkup" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="n_bar">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link nav-new" href="#">مشاوره آنلاین</a></li>
                        <li class="nav-item"><a class="nav-link nav-new" href="#">مشاوره حضوری</a></li>
                        <li class="nav-item"><a class="nav-link nav-new" href="#">دسته تست پدر</a></li>
                        <li class="nav-item"><a class="nav-link nav-new" href="#">تماس با</a></li>
                        <li class="nav-item"><a class="nav-link nav-new" href="#"> مدرس ممتازشو</a></li>
                        <li class="nav-item"><a class="nav-link nav-new" href="#">مقالات</a></li>
                    </ul>
                </div>
            </div>
        </nav>
</head>
<body>
	<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
	  {% for slider_image in slider_images %}
	  	<div class="carousel-item active" data-bs-interval="10000">
	  <img src="{{MEDIA_URL}}{{slider_image.image}}" class="d-block w-100"  alt="...">
	</div>
	  {% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
	<p class="ps mb-2 fs-3">دوره های جدید</p><hr>
	<center><div class="bg-img"><img src="{{MEDIA_URL}}tutorial_images/momtazgroup.jpg" style="width: 75%;"></img></div></center>
<div class="divs">
	{% for tutorial in tutorials %}
		<div class="skewed">
			<div class="image">
					<div><img src="{{MEDIA_URL}}{{tutorial.tutorial_image}}" alt="img"></div>
				</div>
			<div class="text">
				<h2>{{tutorial.tutorial_name}}</h2>
				<p>{{tutorial.tutorial_content}}</p>
				<small>قیمت دوره:{{tutorial.tutorial_price}} تومان</small>
				<a  class="a1" href="#">&rarr;اطلاعات بیشتر</a>
			</div>
		</div>
	{% endfor %}
	</div>
	</div>
	<div style="background-color: transparent;"><iframe  style="width: 100%; height: 70vh;" src="{% url 'dashboard:dashboard-card_slider' %}"></iframe></div>
	<footer class="ftr" dir="ltr">
		<div class="ctr">
			<div class="rw">
				<div class="ftr-col" style="text-align: left;">
					<h4>آموزشگاه</h4>
					<ul>
						<li><a href="#">کلاس</a></li>
						<li><a href="#">دوره</a></li>
						<li><a href="#">همایش</a></li>
						<li><a href="#">جشن</a></li>
					</ul>
				</div>
				<div class="ftr-col">
					<h4>پشتیبانی</h4>
					<ul>
						<li><a href="#">تلفن</a></li>
						<li><a href="#">آدرس</a></li>
						<li><a href="#">تلگرام</a></li>
						<li><a href="#">موسسه</a></li>
					</ul>
				</div>
				<div class="ftr-col">
					<h4>مشاورها</h4>
					<ul>
						<li><a href="#">عزیزمرادی</a></li>
						<li><a href="#">یامینی</a></li>
						<li><a href="#">تاجیک</a></li>
						<li><a href="#">سمسار</a></li>
					</ul>
				</div>
				<div class="ftr-col">
					<h4>دنبال کردن</h4>
					<div class="social-links">
						<a href="#"><i class="fab fa-facebook-f"></i></a>
						<a href="#"><i class="fab fa-twitter"></i></a>
						<a href="#"><i class="fab fa-instagram"></i></a>
						<a href="#"><i class="fab fa-linkedin-in"></i></a>
					</div>
				</div>
			</div>
		</div>
	</footer>
</body>
</html>

dashboard/templates/dashboard/footer.html
{% load static %}
	<footer class="ftr" dir="ltr">
		<div class="ctr">
			<div class="rw">
				<div class="footer-col">
					<h4>آموزشگاه</h4>
					<ul>
						<li><a href="#">کلاس</a></li>
						<li><a href="#">دوره</a></li>
						<li><a href="#">همایش</a></li>
						<li><a href="#">جشن</a></li>
					</ul>
				</div>
				<div class="footer-col">
					<h4>پشتیبانی</h4>
					<ul>
						<li><a href="#">تلفن</a></li>
						<li><a href="#">آدرس</a></li>
						<li><a href="#">تلگرام</a></li>
						<li><a href="#">آدرس خونه ممتاز</a></li>
					</ul>
				</div>
				<div class="footer-col">
					<h4>مشاورها</h4>
					<ul>
						<li><a href="#">عزیزمرادی</a></li>
						<li><a href="#">یامینی</a></li>
						<li><a href="#">تاجیک</a></li>
						<li><a href="#">سمسار</a></li>
					</ul>
				</div>
				<div class="footer-col">
					<h4>دنبال کردن</h4>
					<div class="social-links">
						<a href="#"><i class="fab fa-facebook-f"></i></a>
						<a href="#"><i class="fab fa-twitter"></i></a>
						<a href="#"><i class="fab fa-instagram"></i></a>
						<a href="#"><i class="fab fa-linkedin-in"></i></a>
					</div>
				</div>
			</div>
		</div>
	</footer>
    </div><!--end of element of body-->